[package]
name = "maud-heroicons"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.27.0"

[build-dependencies]
git2 = "0.20.1"
html2maud = "0.1.11"
